languague: java
addons:
  sonarcloud:
    organization: "tangorabox"
    token:
      secure: ${SONAR_TOKEN}

script:
  # the following command line builds the project and then execute the SonarCloud analysis
  - mvn clean install sonar:sonar